project:
  type: website

website:
  title: "Tom Cantellow"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: resources.qmd
        text: Resources

    right:
      - text: CV
        href: assets/CV.pdf
      - text: LinkedIn
        href: https://www.linkedin.com/in/tomcantellow/
      - text: Contact
        href: mailto:tcantellow@gmail.com

format:
  html:
    theme: none
    css: assets/styles.css
    toc: false
